# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

riemann_gradient_cpp <- function(L, D) {
    .Call('_morpca_riemann_gradient_cpp', PACKAGE = 'morpca', L, D)
}

orthographic_retraction_cpp <- function(L_tmp, Q, R) {
    .Call('_morpca_orthographic_retraction_cpp', PACKAGE = 'morpca', L_tmp, Q, R)
}

rank_r_approx_cpp <- function(Y, r) {
    .Call('_morpca_rank_r_approx_cpp', PACKAGE = 'morpca', Y, r)
}

